"""empty message

Revision ID: 60f758dde4af
Revises: 
Create Date: 2020-08-25 16:25:08.617379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f758dde4af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('age_range', sa.Enum('ten', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'na', name='age_range'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belt', sa.SmallInteger(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('injured', sa.String(length=10), nullable=True),
    sa.Column('consec', sa.Integer(), nullable=True),
    sa.Column('conse_g', sa.Integer(), nullable=True),
    sa.Column('conse_m', sa.Integer(), nullable=True),
    sa.Column('conse_sem', sa.Integer(), nullable=False),
    sa.Column('_merge', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighborhood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subbrand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('subbrand_id', sa.Integer(), nullable=True),
    sa.Column('car_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['car_type_id'], ['car_type.id'], ),
    sa.ForeignKeyConstraint(['subbrand_id'], ['subbrand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('intersection_a_id', sa.Integer(), nullable=True),
    sa.Column('intersection_b_id', sa.Integer(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intersection_a_id'], ['street.id'], ),
    sa.ForeignKeyConstraint(['intersection_b_id'], ['street.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhood.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hour', sa.Enum('zero', 'two', 'four', 'six', 'eight', 'ten', 'twelve', 'fourteen', 'sixteen', 'eighteen', 'twenty', 'twentytwo', 'na', name='hour'), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('accident_type_id', sa.Integer(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('affected_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accident_type_id'], ['accident_type.id'], ),
    sa.ForeignKeyConstraint(['affected_id'], ['affected.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.id'], ),
    sa.ForeignKeyConstraint(['detail_id'], ['detail.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accident')
    op.drop_table('place')
    op.drop_table('car')
    op.drop_table('subbrand')
    op.drop_table('street')
    op.drop_table('route')
    op.drop_table('neighborhood')
    op.drop_table('municipality')
    op.drop_table('detail')
    op.drop_table('cause')
    op.drop_table('car_type')
    op.drop_table('brand')
    op.drop_table('affected')
    op.drop_table('accident_type')
    # ### end Alembic commands ###
